/**
 * Daftar domain disposable/temp email yang dikenal.
 * Sumber: https://github.com/disposable-email-domains/public
 */
const DISPOSABLE_DOMAINS: string[] = [
  '0-00.xyz',
  '0815.ru',
  '0clickemail.com',
  '10minutemail.com',
  '1ce.us',
  '1shivom.com',
  '2prong.com',
  '30minutemail.com',
  '33mail.com',
  '3trtretgfrf.xyz',
  '4mail.cf',
  '4mail.ga',
  '4warding.com',
  '5mail.cf',
  '5mail.ga',
  '6ip.us',
  '6paq.com',
  '7tags.com',
  '9mail.cf',
  '9ox.net',
  'a-bc.net',
  'airmailhub.com',
  'alltempemail.com',
  'amilegit.com',
  'anonymousemail.me',
  'anonymbox.com',
  'armyspy.com',
  'atnextmail.com',
  'auti.st',
  'avastc.com',
  'azazazatashkent.tk',
  'bannedpls.xyz',
  'bccto.me',
  'binkmail.com',
  'bio-muesli.net',
  'block-chain.tech',
  'bobmail.info',
  'bongobong.site',
  'boofx.com',
  'boun.cr',
  'boxformail.com',
  'breakthru.com',
  'brefmail.com',
  'brennendesreich.de',
  'broadbandninja.com',
  'bsnow.net',
  'buffemail.com',
  'bumpymail.com',
  'burnthespam.info',
  'c2.hu',
  'cachedot.net',
  'cellurl.com',
  'chielino.com',
  'choicemail1.com',
  'clandest.in',
  'cliptik.net',
  'cmail.club',
  'cobarekyo.xyz',
  'cool.fr.nf',
  'correio.blog.br',
  'courriel.net',
  'courrieltemporaire.com',
  'crapmail.org',
  'crazymailing.com',
  'crossmail.ga',
  'cu.cc',
  'curryworld.de',
  'dab.ro',
  'deadaddress.com',
  'despam.it',
  'devnullmail.com',
  'digiprice.co',
  'discard.email',
  'discard.ga',
  'discard.gq',
  'dispostable.com',
  'dm.w3internet.co.uk',
  'dodgeit.com',
  'dodgemail.de',
  'dontreg.com',
  'dontsendmeshit.com',
  'drdrb.com',
  'dump-email.info',
  'dumpandjunk.com',
  'dumpmail.de',
  'dumpyemail.com',
  'e4ward.com',
  'easytrashmail.com',
  'einrot.com',
  'email-fake.com',
  'email.cbes.net',
  'email.cloudns.cf',
  'email.ucms.edu.pl',
  'email60.com',
  'emailgo.de',
  'emailias.com',
  'emailinfive.com',
  'emailisvalid.com',
  'emaillime.com',
  'emailmiser.com',
  'emails.ga',
  'emailsensei.com',
  'emailspam.it',
  'emailtemporario.com.br',
  'emailto.de',
  'emailwarden.com',
  'emailxr.com',
  'emailz.cf',
  'emailz.ga',
  'emailz.gq',
  'ephemail.net',
  'etranquil.com',
  'etranquil.net',
  'explodemail.com',
  'fakemailgenerator.com',
  'fakemailz.com',
  'fastmailnow.com',
  'fatflap.com',
  'fdfdsfds.com',
  'fightallspam.com',
  'filzmail.com',
  'fivemail.de',
  'fmel.net',
  'free-email.cf',
  'freemail.ms',
  'freemail.tweakly.net',
  'friendlymail.co.uk',
  'fuckingduh.com',
  'fudgerub.com',
  'garliclife.com',
  'gehensiemirnichtaufdensack.de',
  'getairmail.com',
  'getmails.eu',
  'godut.com',
  'gowikibooks.com',
  'gowikicampus.com',
  'gowikigames.com',
  'gowikimusic.com',
  'gowikinetwork.com',
  'gowikitravel.com',
  'gowikitv.com',
  'great-host.in',
  'greensloth.com',
  'grr.la',
  'gsrv.co.uk',
  'guerillamail.com',
  'guerillamail.net',
  'guerillamail.org',
  'guerrillamail.biz',
  'guerrillamail.com',
  'guerrillamail.de',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamailblock.com',
  'h.mintemail.com',
  'h8s.org',
  'haltospam.com',
  'harakirimail.com',
  'hartbot.de',
  'hidemail.de',
  'hideweb.xyz',
  'hmamail.com',
  'hochsitze.com',
  'hopemail.biz',
  'hotpop.com',
  'hstermail.com',
  'i-taiwan.nets.hk',
  'ieatspam.eu',
  'ieatspam.info',
  'ignoremail.com',
  'imails.info',
  'inbox.si',
  'inboxalias.com',
  'inboxbear.com',
  'inoutmail.de',
  'intopwa.com',
  'intopwa.net',
  'ip6.li',
  'ircbox.xyz',
  'ismyemailsecure.com',
  'it7.ovh',
  'jetswap.com',
  'jmail.ovh',
  'jourrapide.com',
  'jsrsolutions.com',
  'junk.to',
  'junk1e.com',
  'junkmail.ga',
  'kademen.com',
  'kavosh.ml',
  'killmail.com',
  'killmail.net',
  'kitties.site',
  'klipsi.de',
  'kobrest.cz',
  'kulturbetrieb.info',
  'kurzepost.de',
  'l33r.xyz',
  'laafd.com',
  'lastmail.co',
  'lazyinbox.com',
  'letthemeatspam.com',
  'linuxmail.so',
  'litedrop.com',
  'lom.kr',
  'lookugly.com',
  'lopl.co.cc',
  'loyalgroups.com',
  'lr78.com',
  'maboard.com',
  'mail-rush.com',
  'mail.by',
  'mail.mezimages.net',
  'mail.ticket-please.ga',
  'mail1a.de',
  'mail21.cc',
  'mail2rss.org',
  'mail4trash.com',
  'mailbidon.com',
  'mailbiz.biz',
  'mailblocks.com',
  'mailbucket.org',
  'mailcat.biz',
  'mailcatch.com',
  'maildrop.cc',
  'maildu.de',
  'maildx.com',
  'maileater.com',
  'mailed.ro',
  'maileimer.de',
  'mailexpire.com',
  'mailf5.com',
  'mailfa.tk',
  'mailfall.com',
  'mailforspam.com',
  'mailfree.ga',
  'mailfree.gq',
  'mailfreemail.ga',
  'mailguard.me',
  'mailgutter.com',
  'mailimate.com',
  'mailinator.com',
  'mailinator.net',
  'mailinator.org',
  'mailinbox.com',
  'mailincubator.com',
  'mailismagic.com',
  'mailita.tk',
  'mailjunk.cf',
  'mailjunk.ga',
  'mailjunk.gq',
  'mailme.ir',
  'mailmetrash.com',
  'mailmoat.com',
  'mailnator.com',
  'mailnesia.com',
  'mailnull.com',
  'mailorg.org',
  'mailpick.biz',
  'mailprotech.com',
  'mailquack.com',
  'mailrocket.biz',
  'mailsac.com',
  'mailscrap.com',
  'mailshiv.com',
  'mailshuttle.com',
  'mailsiphon.com',
  'mailslapping.com',
  'mailslite.com',
  'mailtemp.net',
  'mailtemporaire.com',
  'mailtester.com',
  'mailtrap.io',
  'mailtwister.com',
  'mailup.net',
  'mailvu.com',
  'mailzi.ru',
  'mailzilla.com',
  'mailzilla.org',
  'mbx.cc',
  'mega.zik.dj',
  'meinspamschutz.de',
  'meltmail.com',
  'messagebeamer.de',
  'midosk.xyz',
  'mijnhva.nl',
  'mintemail.com',
  'mjukglass.nu',
  'moakt.com',
  'mobileninja.co.uk',
  'mohmal.com',
  'moncourrier.fr.nf',
  'monemail.fr.nf',
  'monmail.fr.nf',
  'msa.minsmail.com',
  'mt2009.com',
  'mx0.wwwnew.eu',
  'mycleaninbox.net',
  'myemailboxy.com',
  'myopang.com',
  'mypartyclip.de',
  'mytrashmail.com',
  'mytrashmailer.com',
  'neko.xyz',
  'nemre.com',
  'neomailbox.com',
  'nepwk.com',
  'nervmich.net',
  'netmails.com',
  'netmails.net',
  'netzidiot.de',
  'neverbox.com',
  'nice-4u.com',
  'nincsmail.com',
  'nincsmail.hu',
  'nmail.cf',
  'nnh.com',
  'nobulk.com',
  'noclickemail.com',
  'nogmailspam.info',
  'nomail.cf',
  'nomail.ga',
  'nomail.gq',
  'nomail.xl.cx',
  'nomorespamemails.com',
  'nonspam.eu',
  'nonspammer.de',
  'noref.in',
  'nospam.ze.tc',
  'nospam4.us',
  'nospamfor.us',
  'nospamthanks.info',
  'nothingtoseehere.ca',
  'notmailinator.com',
  'nowhere.org',
  'ntlhelp.net',
  'nwldx.com',
  'objectmail.com',
  'obobbo.com',
  'odnorazovoe.ru',
  'oneoffemail.com',
  'onemail.cf',
  'onemail.ga',
  'onemail.gq',
  'oopi.org',
  'opayq.com',
  'ordinaryamerican.net',
  'otherinbox.com',
  'outlawspam.com',
  'ovpn.to',
  'owlpic.net',
  'pancakemail.com',
  'paq9.com',
  'pcusers.otherinbox.com',
  'pepbot.com',
  'pfui.ru',
  'pigpig.xyz',
  'pizmails.com',
  'plexolan.de',
  'poczta.onet.pl',
  'ポスト.com',
  'privacy.net',
  'privy-mail.com',
  'privymail.de',
  'projectcl.com',
  'projctr.com',
  'proxymail.eu',
  'prtnx.com',
  'punkass.com',
  'put2.net',
  'putama.com',
  'qip.ru',
  'rcpt.at',
  'reality-concept.club',
  'reallymymail.com',
  'receiveee.com',
  'recipeforfailure.com',
  'rekv.nl',
  'rhyta.com',
  'rklips.com',
  's0ny.cf',
  's2spam.com',
  'safetymail.info',
  'sale.cf',
  'sale.ga',
  'sale.gq',
  'sandelf.de',
  'saynotospams.com',
  'scrn.site',
  'secmail.ninja',
  'selfdestructingmail.com',
  'sendspamhere.com',
  'shhmail.com',
  'shut.name',
  'shut.ws',
  'sify.com',
  'sinnlos-mail.de',
  'siteposter.com',
  'skeefmail.com',
  'skrx.tk',
  'slaskmail.se',
  'slipry.net',
  'slopsbox.com',
  'slushmail.com',
  'smap.4nmv.ru',
  'smashmail.de',
  'smellfear.com',
  'snakemail.com',
  'sneakemail.com',
  'sneakmail.de',
  'snkmail.com',
  'softpls.asia',
  'sogetthis.com',
  'sohus.cn',
  'solestmail.com',
  'soodomail.com',
  'soodonims.com',
  'spacebunny.xyz',
  'spam-be-gone.com',
  'spam.care',
  'spam.la',
  'spam.su',
  'spam4.me',
  'spamail.de',
  'spamania.net',
  'spamarrest.com',
  'spamavert.com',
  'spambob.com',
  'spambob.net',
  'spambob.org',
  'spambog.com',
  'spambog.de',
  'spambog.net',
  'spambog.ru',
  'spambox.info',
  'spambox.irishspringrealty.com',
  'spambox.me',
  'spambox.org',
  'spambox.us',
  'spamcannon.com',
  'spamcannon.net',
  'spamcero.com',
  'spamcon.org',
  'spamcorptastic.com',
  'spamcowboy.com',
  'spamcowboy.net',
  'spamcowboy.org',
  'spamday.com',
  'spamex.com',
  'spamfighter.cf',
  'spamfighter.ga',
  'spamfighter.gq',
  'spamfree.eu',
  'spamgoes.in',
  'spamgourmet.com',
  'spamgourmet.net',
  'spamgourmet.org',
  'spamhereplease.com',
  'spamhole.com',
  'spamify.com',
  'spaminator.de',
  'spamkill.info',
  'spaml.com',
  'spaml.de',
  'spammotel.com',
  'spamobox.com',
  'spamoff.de',
  'spamsalad.in',
  'spamslicer.com',
  'spamspameverywhere.com',
  'spamstack.net',
  'spamthis.co.uk',
  'spamthisplease.com',
  'spamtrail.com',
  'spamtroll.net',
  'speed.1s.fr',
  'spoofmail.de',
  'spritzzone.de',
  'spys.xyz',
  'squizzy.de',
  'ssoia.com',
  'stexsy.com',
  'stop-my-spam.cf',
  'stop-my-spam.ga',
  'stop-my-spam.gq',
  'storj99.com',
  'stuffmail.de',
  'sudeepga.ga',
  'suioe.com',
  'super-auswahl.de',
  'supermassive.black',
  'suremail.info',
  'sweetxxx.de',
  'swift10minutemail.com',
  'tafmail.com',
  'tagmymail.com',
  'tagyourself.com',
  'talkinator.com',
  'tapchicuoihoi.com',
  'temp-emails.com',
  'temp-mail.com',
  'temp-mail.de',
  'temp-mail.org',
  'tempail.com',
  'tempalias.com',
  'tempe-mail.com',
  'tempemail.biz',
  'tempemail.co',
  'tempemail.co.za',
  'tempemail.com',
  'tempemail.net',
  'tempemail.org',
  'tempinbox.co.uk',
  'tempinbox.com',
  'tempmail.co',
  'tempmail.it',
  'tempmail.pro',
  'tempmail.space',
  'tempmail2.com',
  'tempmaildemo.com',
  'tempmailer.com',
  'tempmailer.de',
  'tempomail.fr',
  'temporarily.de',
  'temporarioemail.com.br',
  'temporary-email.com',
  'temporary.xyz',
  'temporaryemail.net',
  'temporaryemail.us',
  'temporariemail.com.br',
  'tempsky.com',
  'tempthe.net',
  'thankyou2010.com',
  'thc.st',
  'theaviors.com',
  'thelightmail.com',
  'themailpro.net',
  'thisisnotmyrealemail.com',
  'thismail.net',
  'throwaway.email',
  'throwaway.io',
  'throwaway.xyz',
  'throwaways.xyz',
  'tittbit.in',
  'tmail.ws',
  'toddsbighug.com',
  'toiea.com',
  'topinrock.cf',
  'tormail.org',
  'trandefine.com',
  'trash-amil.com',
  'trash-mail.at',
  'trash-mail.cf',
  'trash-mail.ga',
  'trash-mail.gq',
  'trash-me.com',
  'trash2009.com',
  'trash2010.com',
  'trash2011.com',
  'trash2012.com',
  'trash2013.com',
  'trashdevil.com',
  'trashemail.de',
  'trashemails.de',
  'trashinbox.net',
  'trashmail.at',
  'trashmail.com',
  'trashmail.de',
  'trashmail.gq',
  'trashmail.me',
  'trashmail.net',
  'trashmail.org',
  'trashmail.ws',
  'trashmailer.com',
  'trashmailer.de',
  'trashmails.com',
  'trashymail.com',
  'trashymail.net',
  'trbvm.com',
  'trialmail.de',
  'trillianpro.com',
  'tryalert.com',
  'turual.com',
  'twinmail.de',
  'tyldd.com',
  'uggsrock.com',
  'umail.net',
  'unlimit.com',
  'upliftnow.com',
  'uplipht.com',
  'upyourkarma.com',
  'valemail.net',
  'vektik.com',
  'vemomail.win',
  'venompen.com',
  'veryrealemail.com',
  'viditbhatia.com',
  'viewcastmedia.com',
  'viewcastmedia.net',
  'viewcastmedia.org',
  'viroleni.cu.cc',
  'vnedu.me',
  'vodkaboys.xyz',
  'voidbay.com',
  'vomoto.com',
  'vpn.st',
  'vr5.ovh',
  'vsimcard.com',
  'vsob.com',
  'vssms.com',
  'vysor.me',
  'w3internet.co.uk',
  'wbml.net',
  'webemail.me',
  'webm4il.info',
  'webuser.in',
  'wee.my',
  'weg-werf-email.de',
  'wegwerf-email-addressen.de',
  'wegwerf-email-adressen.de',
  'wegwerf-email.at',
  'wegwerf-email.de',
  'wegwerf-email.net',
  'wegwerf-emails.de',
  'wegwerfadresse.de',
  'wegwerfmail.com',
  'wegwerfmail.de',
  'wegwerfmail.net',
  'wegwerfmail.org',
  'wh4f.org',
  'whyspam.me',
  'wibblesmith.com',
  'willselfdestruct.com',
  'winemaven.info',
  'wronghead.com',
  'wuzup.net',
  'wzip.net',
  'wzzz.xyz',
  'x24.com',
  'xagloo.com',
  'xemaps.com',
  'xents.com',
  'xmaily.com',
  'xoxy.net',
  'xrho.com',
  'yapped.net',
  'yep.it',
  'yogamaven.com',
  'yopmail.com',
  'yopmail.fr',
  'yopmail.net',
  'yopmail.org',
  'ypmail.webarnak.com',
  'yuurok.com',
  'zehnminutenmail.de',
  'zetmail.com',
  'zippymail.info',
  'zoaxe.com',
  'zoemail.com',
  'zoemail.org',
  'zombie-hive.com',
  'zomg.info',
  'zxcv.com',
  'zxcvbnm.com',
  'zzz.com',
];

/**
 * Ekspresi reguler untuk validasi format email dasar.
 * - Local part: huruf, angka, underscore, tanda hubung
 * - Domain: huruf, angka, tanda hubung, dengan setidaknya satu titik
 * - Tidak mengizinkan titik, plus, atau karakter khusus lainnya di local part
 */
const EMAIL_REGEX = /^[a-zA-Z0-9_-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;

/**
 * normalizeGmail — Normalisasi alamat Gmail untuk pengecekan duplikat.
 *
 * Gmail mengabaikan tanda titik dan apapun setelah + di local part.
 * Fungsi ini menghapus semua titik dan bagian +alias, lalu mengubah
 * semuanya menjadi huruf kecil.
 *
 * Contoh:
 *   normalizeGmail("h.i.l.m.i+test@gmail.com") → "hilmi@gmail.com"
 *   normalizeGmail("User.Name+spam@GMail.com") → "username@gmail.com"
 *
 * @param email - Alamat email yang akan dinormalisasi
 * @returns Alamat email yang sudah dinormalisasi (lowercase, tanpa titik, tanpa +alias)
 */
export function normalizeGmail(email: string): string {
  const lowercased = email.toLowerCase().trim();

  // Pastikan email mengandung @
  const atIndex = lowercased.indexOf('@');
  if (atIndex === -1) {
    return lowercased;
  }

  const localPart = lowercased.slice(0, atIndex);
  const domain = lowercased.slice(atIndex);

  // Hanya terapkan normalisasi untuk domain Gmail
  if (domain !== '@gmail.com') {
    return lowercased;
  }

  // Hapus apapun setelah tanda + (plus alias)
  const plusIndex = localPart.indexOf('+');
  const strippedLocal = plusIndex === -1 ? localPart : localPart.slice(0, plusIndex);

  // Hapus semua tanda titik dari local part
  const noDotsLocal = strippedLocal.replace(/\./g, '');

  return `${noDotsLocal}@gmail.com`;
}

/**
 * validateEmail — Validasi alamat email untuk registrasi.
 *
 * Fungsi ini memeriksa:
 * 1. Email tidak boleh kosong
 * 2. Format email harus sesuai dengan pola dasar (local@domain)
 * 3. Domain harus @gmail.com (hanya Gmail yang diizinkan)
 * 4. Local part tidak boleh mengandung tanda titik (.)
 * 5. Local part tidak boleh mengandung tanda plus (+) / alias
 * 6. Domain tidak boleh termasuk dalam daftar disposable/temp email
 *
 * Jika valid, mengembalikan objek dengan `valid: true` dan `normalizedEmail`
 * yang sudah dinormalisasi. Jika tidak valid, mengembalikan pesan error.
 *
 * @param email - Alamat email yang akan divalidasi
 * @returns Objek hasil validasi
 */
export function validateEmail(
  email: string,
): { valid: true; normalizedEmail: string } | { valid: false; error: string } {
  // 1. Cek apakah email kosong atau tidak diisi
  if (!email || email.trim().length === 0) {
    return { valid: false, error: 'Email tidak boleh kosong' };
  }

  const trimmedEmail = email.trim();

  // 2. Cek format dasar dengan regex
  if (!EMAIL_REGEX.test(trimmedEmail)) {
    return {
      valid: false,
      error: 'Format email tidak valid. Gunakan format: nama@domain.com',
    };
  }

  // 3. Pastikan domain adalah @gmail.com
  if (!trimmedEmail.toLowerCase().endsWith('@gmail.com')) {
    return {
      valid: false,
      error: 'Hanya alamat @gmail.com yang diizinkan untuk registrasi',
    };
  }

  // Ambil local part (bagian sebelum @)
  const atIndex = trimmedEmail.indexOf('@');
  const localPart = trimmedEmail.slice(0, atIndex);

  // 4. Cek apakah local part mengandung tanda titik (.)
  //    Gmail mengabaikan titik, jadi user.name sama dengan username
  if (localPart.includes('.')) {
    return {
      valid: false,
      error: 'Alamat Gmail tidak boleh mengandung tanda titik (.) di bagian lokal',
    };
  }

  // 5. Cek apakah local part mengandung tanda plus (+) / alias
  //    Gmail mengabaikan apapun setelah +, jadi user+spam = user
  if (localPart.includes('+')) {
    return {
      valid: false,
      error: 'Alamat Gmail tidak boleh mengandung tanda plus (+) / alias',
    };
  }

  // 6. Ambil domain untuk pengecekan disposable
  const domain = trimmedEmail.slice(atIndex + 1).toLowerCase();

  // Cek apakah domain termasuk dalam daftar disposable
  if (DISPOSABLE_DOMAINS.includes(domain)) {
    return {
      valid: false,
      error: 'Alamat email sekali pakai (disposable/temp email) tidak diizinkan',
    };
  }

  // Semua validasi lolos — kembalikan email yang sudah dinormalisasi
  const normalizedEmail = normalizeGmail(trimmedEmail);

  return { valid: true, normalizedEmail };
}
